version: "3.9"
services:
  vite:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    ports:
      - "4000:4000"
    user: "${UID_GID}"
    volumes:
      - /projects/misc/2021/webxr-test003:/app
